source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'MEVFloatingButton_Example', :exclusive => true do
  pod 'MEVFloatingButton', :path => '../'
end

target 'MEVFloatingButton_Tests', :exclusive => true do
  pod 'MEVFloatingButton', :path => '../'

  
end
